# Generated by Django 3.2 on 2022-03-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='step',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='equipment',
            name='kind',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='maker',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_size_units',
            field=models.IntegerField(choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Milliliters'), (4, 'Liters'), (5, 'Pinches')], default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipy.recipe'),
        ),
        migrations.CreateModel(
            name='IntegredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('amount_units', models.IntegerField(choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Milliliters'), (4, 'Liters'), (5, 'Pinches')], default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipy.ingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipy.step')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='step',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='recipy.process'),
            preserve_default=False,
        ),
    ]
