# Generated by Django 3.2 on 2022-03-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0002_auto_20220331_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('amount_units', models.IntegerField(choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Milliliters'), (4, 'Liters'), (5, 'Pinches'), (6, 'Unit')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='serving_size_units',
            field=models.IntegerField(choices=[(1, 'Grams'), (2, 'Kilograms'), (3, 'Milliliters'), (4, 'Liters'), (5, 'Pinches'), (6, 'Unit')], default=1),
        ),
        migrations.DeleteModel(
            name='IntegredientUsage',
        ),
        migrations.AddField(
            model_name='ingredientusage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipy.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientusage',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipy.step'),
        ),
    ]
