# Generated by Django 3.2 on 2022-03-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0003_auto_20220331_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='active_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='makes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='passive_time',
            field=models.IntegerField(null=True),
        ),
    ]
